### PR TITLE
Fix roundtrip test

### LINKED ISSUE #45: Unquoted strings are parsed as identifiers
Both identifiers and unquoted strings are pretty-printed the same way, but identifier parsing has higher priority than string parsing during parsing stage, causing the following behavior:
```haskell
ghci> import Language.Jsonnet.Syntax
ghci> import Language.Jsonnet.Common
ghci> import Language.Jsonnet.Pretty
ghci> import Language.Jsonnet.Test.Roundtrip
ghci> import qualified Data.Text as T
ghci> e = EStr "foo" Unquoted
ghci> parseExpr . T.pack . show . ppExpr $ e
Right (Fix (InL (EIdent "foo")))
```
This causes roundtrip tests to sometimes fail, since a pretty-printed unquoted string is later parsed as an identifier. Here is a hedgehog seed to see an example failing roundtrip test:
```bash
cabal run jsonnet-test -- -p "roundtrip" --hedgehog-replay "Size 91 Seed 12461984714529812419 8668381392682229415"
```

### PR DESCRIPTION
**Pull request by ozkutuk**
Closes #45

As discussed in the comments of #45, the lookup expression did not conform to the Jsonnet specification. Interestingly enough, the roundtrip test seemed to be fixed on its own after I have changed the definition of the lookup expression. Still, I have also removed the unquoted strings altogether, since they weren't really needed anymore. However, I am not 100% confident in the potential implications of this change, so it would be a good idea to review this thoroughly before merging.

### CODE REVIEW

**Comment by ozkutuk** [comment]
Pipeline seems to be failing since it can't install GHC 9.0.1. I don't know what changed since my last PR but `actions/setup-haskell` is marked as deprecated either way, so it might be a good idea to migrate to [`haskell/actions/setup`](https://github.com/haskell/actions).

File: src/Language/Jsonnet/Parser.hs [hunk 1]
```diff
@@ -343,10 +342,11 @@ objectP = Fix <$> annotateLoc (braces (try objectComp <|> object)) <?> "object"
           <$> option False (symbol "+" $> True) <*> sepP
       value <- exprP
       pure $ EField {..}
-    keyP = ((, True) <$> brackets exprP) <|> ((, False) <$> (unquoted <|> stringP))
+    keyP = ((,True) <$> brackets exprP) <|> ((,False) <$> (identStringP <|> stringP))
```
Comment (moleike) [inline src/Language/Jsonnet/Parser.hs:345]: note here that we are losing information (the fact that it's a valid identifier and thus jsonnet allows it to be unquoted). That's the reason I suggested have a separate type for keys. Maybe we can add an additional flag for when it's unquoted so that the pretty-printer can use that?

**Review by moleike — COMMENTED** [review]
I need to look into it a bit more carefully but looks good 🙌

File: src/Language/Jsonnet/Parser.hs (hunk 1 above)
Comment (moleike) [reply src/Language/Jsonnet/Parser.hs:345]: Seeing this now after my comments on the pretty printer, perhaps is not worth to change anything here, so resolved!

**Comment by ozkutuk** [comment]
@moleike I also think that we can leave this as is and return back if it poses to be a problem once we make use of the pretty-printing module within the codebase.
